[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@forge-std/=lib/forge-std/src/",
    "@interfaces/=src/interfaces/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
